[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "whisper_live"
dynamic = ["version"]
description = "A nearly-live implementation of OpenAI's Whisper."
readme = "README.md"
authors = [
    {name = "Collabora Ltd", email = "vineet.suryan@collabora.com"}
]
urls = {Homepage = "https://github.com/collabora/WhisperLive"}
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.9"
dependencies = [
    "scipy",
    "numpy<2",
]

[project.optional-dependencies]
client = [
    "PyAudio",
    "av",
    "websocket-client",
]
server = [
    "faster-whisper==1.1.0",
    "websockets",
    "onnxruntime==1.17.0",
    "numba",
    "kaldialign",
    "soundfile",
    "av",
    "jiwer",
    "evaluate",
    "openai-whisper==20240930",
    "tokenizers==0.20.3",
    "transformers[torch]",
    "sentencepiece",

    # openvino
    "librosa",
    "openvino",
    "openvino-genai",
    "openvino-tokenizers",
    "optimum ",
    "optimum-intel",
]

[project.scripts]
run-server = "whisper_live.scripts.run_server:main"
run-client = "whisper_live.scripts.run_client:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
exclude = [
    "examples",
    "Audio-Transcription-Chrome",
    "Audio-Transcription-Firefox",
    "requirements",
    "whisper-finetuning"
]

[tool.setuptools.dynamic]
version = {file = ["VERSION"]}
